name: Push docusaurus documentation

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

on:
  push:
    branches:
      - main
      - docs
      - architecture-introduction

    paths:
      - 'packages/react-bindings/**'
      - 'packages/client/**'
      - 'packages/react-native-sdk/**'
      - 'packages/react-sdk/**'
      - '.github/workflows/docusaurus-deploy.yml'

jobs:
  push_docusaurus:
    name: Build and deploy the documentation
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --immutable

      - name: Generate React Native SDK documentation
        run: yarn generate-docs:react-native:sdk;
      - name: Push React Native SDK documentation
        uses: GetStream/push-stream-chat-docusaurus-action@main
        with:
          target-branch: 'staging'
          destination-repository-name: 'stream-video-docusaurus'
          source-directory: 'packages/react-native-sdk/docusaurus'
        env:
          DOCUSAURUS_GH_TOKEN: ${{ secrets.DOCUSAURUS_GH_TOKEN }}

      - name: Generate React SDK documentation
        run: yarn generate-docs:react:sdk
      - name: Push React SDK documentation
        uses: GetStream/push-stream-chat-docusaurus-action@main
        with:
          target-branch: 'staging'
          destination-repository-name: 'stream-video-docusaurus'
          source-directory: 'packages/react-sdk/docusaurus'
        env:
          DOCUSAURUS_GH_TOKEN: ${{ secrets.DOCUSAURUS_GH_TOKEN }}
